"""Register user-authored strategies as versioned agents.

A plain-English strategy becomes a first-class agent that appears in the
gallery, runs on demand, and is ranked on the same leaderboard as the built-in
ones — with no code written by the user and none generated by the platform.

**Security note (why this is safe):** an authored strategy is never Python. The
natural-language text compiles to a *rule spec* — plain data (indicators,
comparisons, thresholds) — which the existing deterministic ``RuleSpecStrategy``
runtime interprets. There is no ``eval``, no generated source, and no import of
user content, so authoring cannot execute arbitrary code. The spec is validated
against the runtime's declared capabilities before it can run at all.

**Versioning:** registration is append-only. Editing an authored strategy
creates ``v2`` rather than mutating ``v1``, so old runs and scores keep pointing
at the exact spec that produced them (lineage), and a leaderboard entry can
never silently change meaning.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..agents.base import AgentResult, AgentTask
from ..db import connect


def _utc_now() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


def _slug(name: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", "_", (name or "").lower()).strip("_")
    return cleaned or "authored_strategy"


class AuthoredAgentService:
    def __init__(
        self,
        db_path: Path,
        custom_strategies: Any,
        optimizer: Any,
        dataset_resolver: Any,
    ) -> None:
        self.db_path = db_path
        self.custom_strategies = custom_strategies
        self.optimizer = optimizer
        self.dataset_resolver = dataset_resolver

    # -- registration ---------------------------------------------------------

    def register_from_spec(
        self, *, spec_id: str, author: str = "user"
    ) -> dict[str, Any]:
        """Register a saved rule spec as an agent, versioning on re-register."""

        record = self.custom_strategies.get_spec(spec_id)
        spec = record["spec"]
        validation = record.get("validation") or {}
        if validation.get("missing_capabilities"):
            raise ValueError(
                "This strategy needs review before it can be registered: "
                f"{validation['missing_capabilities']}"
            )
        name = _slug(spec.get("name") or record.get("name") or spec_id)
        version = self._next_version(name)
        agent_id = f"{name}@{version}"
        symbol = (spec.get("symbol") or "").upper() or None
        con = connect(self.db_path)
        try:
            con.execute(
                "INSERT INTO agents VALUES (?, ?, ?, 'strategy', ?, ?, ?, ?, "
                "'active', ?)",
                [
                    agent_id,
                    name,
                    version,
                    (
                        spec.get("description")
                        or f"Authored strategy on {symbol or 'the market'}."
                    ),
                    json.dumps(["backtest", "validate", "authored"]),
                    json.dumps({"spec_id": spec_id, "symbol": symbol}),
                    author,
                    _utc_now(),
                ],
            )
        finally:
            con.close()
        return {
            "agent_id": agent_id,
            "name": name,
            "version": version,
            "spec_id": spec_id,
            "symbol": symbol,
            "status": "registered",
        }

    def _next_version(self, name: str) -> str:
        """Append-only versioning: 1.0, 2.0, ... so lineage is never lost."""
        con = connect(self.db_path)
        try:
            rows = con.execute(
                "SELECT version FROM agents WHERE name = ?", [name]
            ).fetchall()
        finally:
            con.close()
        majors = []
        for (version,) in rows:
            try:
                majors.append(int(str(version).split(".")[0]))
            except ValueError:
                continue
        return f"{(max(majors) + 1) if majors else 1}.0"

    def list_authored(self) -> dict[str, Any]:
        con = connect(self.db_path)
        try:
            rows = con.execute(
                "SELECT agent_id, name, version, description, config_json, "
                "author, created_at FROM agents "
                "WHERE category = 'strategy' AND author != 'platform' "
                "ORDER BY created_at DESC"
            ).fetchall()
        finally:
            con.close()
        return {
            "authored": [
                {
                    "agent_id": r[0],
                    "name": r[1],
                    "version": r[2],
                    "description": r[3],
                    "config": json.loads(r[4]) if r[4] else {},
                    "author": r[5],
                    "created_at": r[6].isoformat() if isinstance(r[6], datetime) else str(r[6]),
                }
                for r in rows
            ]
        }

    # -- execution ------------------------------------------------------------

    def run_authored(self, agent_id: str, task: AgentTask) -> AgentResult:
        """Walk-forward the authored spec — the same scoring path as built-ins."""

        con = connect(self.db_path)
        try:
            row = con.execute(
                "SELECT config_json FROM agents WHERE agent_id = ?", [agent_id]
            ).fetchone()
        finally:
            con.close()
        if row is None:
            return AgentResult(status="failed", gaps=[f"unknown agent {agent_id!r}"])
        config = json.loads(row[0]) if row[0] else {}
        spec_id = config.get("spec_id")
        symbol = task.symbol or config.get("symbol")
        if not spec_id:
            return AgentResult(
                status="failed", gaps=["this agent has no strategy spec on file"]
            )
        try:
            spec = self.custom_strategies.get_spec(spec_id)["spec"]
            dataset_id = self.dataset_resolver(symbol, task.exchange)
            if not dataset_id:
                return AgentResult(
                    status="partial",
                    gaps=[f"no stored market data for {symbol}"],
                )
            findings = self.optimizer.walk_forward_spec(
                dataset_id=dataset_id, spec=spec
            )
        except Exception as exc:  # noqa: BLE001 - reported, not raised
            return AgentResult(status="failed", gaps=[str(exc)[:300]])
        return AgentResult(
            status="ok",
            findings=findings,
            evidence=[
                {
                    "kind": "walk_forward_split",
                    "dataset_id": dataset_id,
                    "train_bars": findings.get("train_bars"),
                    "test_bars": findings.get("test_bars"),
                    "spec_id": spec_id,
                }
            ],
            gaps=[],
        )
